# global configuration attributes
global:
  tags:
    room: room name
    site: site name
  scrap_interval: 0.5 # s
  http_server_port: 8000

SAES:
  IP: 127.0.0.1 #10.1.0.10
  port: 2527
  location: SAES ion pump
  name_prefix: SAES_ion_pump_

